### ISSUE TITLE
Plugin is not compatible with latest EAP

### ISSUE THREAD

**Issue by b1rdex** [Haehnchen/idea-php-annotation-plugin#105]
IDE disables it on start.

PhpStorm 2018.1 EAP
Build #PS-181.3494.16, built on February 7, 2018
PhpStorm EAP User
Expiration date: March 9, 2018
JRE: 1.8.0_152-release-1136-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by narrishinsd** [comment]
...which means the Symfony plugin errors out as it depends on this one...

**Comment by nicolas-santos** [comment]
same here… downgrading…

**Comment by crabnky** [comment]
same here...

**Comment by rudiedirkx** [comment]
How do you see PS disables it? It seems to be enabled (checkbox checked), but it doesn't do anything. (Clicking on @Annotation doesn't goto, and annotation imports are unused.) Logs? Errors? I don't see anything.

**Comment by vkhramtsov** [comment]
@rudiedirkx You can check event log in phpstorm. Just click on notifications counter in left bottom corner of IDE window.

**Comment by King2500** [comment]
![image](https://user-images.githubusercontent.com/4896363/36140569-016d2638-10a2-11e8-86f9-d2ad14e125af.png)

From idea.log:
```
2018-02-13 09:38:29,305 [   5038]   INFO - llij.ide.plugins.PluginManager - Plugin 'PHP Annotations' can't be loaded because: This plugin version was marked as incompatible 
```

**Comment by rudiedirkx** [comment]
Ah yes I see it in `idea.log`, but not in the UI Events window. Reverting back works. Now we wait for @Haehnchen ?

**Comment by Besedin86** [comment]
Have the same issue

**Comment by matiux** [comment]
Same issue

**Comment by cetver** [comment]
Have the same issue

**Comment by Hunternnm** [comment]
@Haehnchen ?

**Comment by pbelyaev** [comment]
It's been 8 days, is there any solution yet?

**Comment by vkhramtsov** [comment]
I can at least try to fix this, but I have problems with java. Can somebody help me with PR?

**Comment by Hunternnm** [comment]
@Haehnchen release?

**Comment by narration-sd** [comment]
@Haehnchen  Thanks kindly for doing the work on your weekend, David.

I'm sure it will show up in due course once @jetbrains can review it.

**Comment by b1rdex** [comment]
I don't think that new version will be created automatically, becuase there is no new tag done and IDEA banned 5.2.1 version number.

**Comment by vkhramtsov** [comment]
@fintem There is only [idea-version since-build="171.3780"](https://github.com/Haehnchen/idea-php-annotation-plugin/blob/master/META-INF/plugin.xml#L63) but don't have until-build. So may be it can be fixed just by creating new release

**Comment by Haehnchen** [comment]
set since-build to latest eap and released a new version including the changes

**Comment by tarlepp** [comment]
Seems like this issue exists with stable 2018.1 version - any updates?

**Comment by Majkl578** [comment]
Worked for me in 2018.1 RC and still works in 2018.1...

**Comment by tarlepp** [comment]
Hmm, take second look of this, and for some reason  in my setup PHP Annotations was in version 5.2.1 and didn't show any update messages for that - so after manual update it worked as expected.

**Comment by ninsky** [comment]
PhpStorm 18.1. ...had to reinstall Symfony plugin and PHP Annotations plugin to make it work

**Comment by pppdns** [comment]
Auto update suggested this update for me when PHPStorm started (2018.1.1 EAP), I didn't have to manually update it or reinstall anything
