### ISSUE TITLE
Define navigation behaviour for @property

### ISSUE THREAD

**Issue by benito103e** [Haehnchen/idea-php-annotation-plugin#106]
Hello,
Thanks for this great plugin. 

When I set an "@property" annotation on a class : PHPStorm understand that this property is reachable and I can navigate to @property annotation directly.

But most of the time, I would like to navigate to class attribute (if it exists) instead of @property declaration.
Could it be possible to defined the behaviour of the navigation on plugin settings ?

**Comment by cedricziel** [comment]
That's standard PHPStorm behaviour. IMHO, `@property` should be used only for virtual properties represented by `__get` and `__set` - which do not have fields to navigate to.

**Comment by Haehnchen** [comment]
as mentioned "@Property" navigation is done by PhpStorm. You can report inside PhpStorm issue system
