### ISSUE TITLE
Auto complete suggestion of Annotation in Annotation does not work

### ISSUE THREAD

**Issue by magnetik** [Haehnchen/idea-php-annotation-plugin#109]
Hi,

Using PHPStorm 2017.3, when trying to add annotation like:

```
<?php
use Doctrine\ORM\Mapping as ORM;
/** 
 * @ORM\Table(uniqueConstraint={@ORM\<TAB>
class Foo
```

When typing the <TAB>, no auto completion suggestion appears.

**Comment by Haehnchen** [comment]
this is not really possible. you need to provide a valid doc block synax here. its implemented by not on incomplete code

**Comment by cedricziel** [comment]
Closing as wontfix according to the statement above.
