### ISSUE TITLE
PHP annotations plugin won't load in new PHPStorm build 2018.1

### ISSUE THREAD

**Issue by markozivanovic** [Haehnchen/idea-php-annotation-plugin#114]
The following plugins are incompatible with the current IDE build: PHP Annotations.

 System Version:	macOS 10.13.3 (17D102)
 Kernel Version:	Darwin 17.4.0

**Comment by Glideh** [comment]
Same here with

> PhpStorm 2018.1
> Build #PS-181.4203.565, built on March 28, 2018
> JRE: 1.8.0_152-release-1136-b20 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Linux 3.16.0-4-amd64

**Comment by h1k3r** [comment]
https://github.com/Haehnchen/idea-php-annotation-plugin/issues/108#issuecomment-377796377 please check this comment, worked for me

**Comment by markozivanovic** [comment]
Seems it works with all platforms. Thanks!

**Comment by asit910123** [comment]
thanks!! it works!!

**Comment by soopermouse** [comment]
THis is not working. The fix doesn;t work for me
