### ISSUE TITLE
(Aliased) sub-namespaces uses in annotations are not detected

### ISSUE THREAD

**Issue by Taluu** [Haehnchen/idea-php-annotation-plugin#116]
As far as annotations goes, looks like it is working as intended, but in some annotations, we may use a class name (`::class`).

It is correctly detected on class aliases (`use Foo\Bar as FooBar`, `@MyAnnot(FooBar::class)`), but it doesn't seem to be the case with sub-namespaces (and thus subnamespaces aliases) : `use Foo;` ... `@MyAnnot(Foo\Bar::class)` or `use Foo as Qux;` ... `@MyAnnot(Qux\Bar::class)`.

Here are some screens provided by @iltar :

![image 2](https://user-images.githubusercontent.com/239685/39570243-09a8f3a4-4ec8-11e8-893e-799202052335.png)

![image 3](https://user-images.githubusercontent.com/239685/39570248-0b93390e-4ec8-11e8-8d01-0d63b28287ab.png)

![image 4](https://user-images.githubusercontent.com/239685/39570255-0d95d6a8-4ec8-11e8-9a64-e5ed76d00a6a.png)

**Comment by Haehnchen** [comment]
done
