### ISSUE TITLE
Very High CPU usage with PHPStorm 2018.2 on MacOS

### ISSUE THREAD

**Issue by willemnviljoen** [Haehnchen/idea-php-annotation-plugin#124]
When enabling the plugin in PHPStorm 2018.2 on MacOS (10.13.6), CPU usage for the PHPStorm process exceeds 300%.

With the plugin disabled, usage returns to normal. This did not manifest with the most recent patch of 2018.1, so it's likely a compatibility or optimisation issue with 2018.2

**Comment by klipach** [comment]
I have the same issue on MacOS (10.13.6) with PHPStorm 2018.2 and Annotation Plugin 5.3. 

After disabling the plugin CPU load decreases from 300% to normal value.

With PHPStorm 2018.1 there were no issues.

**Comment by cedricziel** [comment]
Hi, is this still an issue?

**Comment by Haehnchen** [comment]
old issue; guess fixed somehow
