### ISSUE TITLE
PhpDocTagReference should not be referenced to the variables

### ISSUE THREAD

**Issue by wbars** [Haehnchen/idea-php-annotation-plugin#126]
As result of fixing #59 `PhpDocTagReference` now is referenced to all `PhpNamedElement` offsprings which can lead to some problems (e.g. https://youtrack.jetbrains.com/issue/WI-39293, there `@var` is referenced to the `$var`), since `Variable` is `PhpNamedElement` as well.

While collecting the occurrences of the variables in _introduce variable_ refactoring we are taking into account `PsiReference::isReferenceTo`, so `@var` is counted as reference to the variable `$var`. I think the easiest solution will be to change `instanceof` check [at this line](https://github.com/Haehnchen/idea-php-annotation-plugin/blob/master/src/main/java/de/espend/idea/php/annotation/reference/DocTagNameAnnotationReferenceContributor.java#L118) to something less general like (`element instanceof PhpClass || element 
 instanceof PhpNamespace`), but I'm not deep into this code so please verify my proposal before implementing.

**Comment by King2500** [comment]
@Haehnchen can you hotfix this?
maybe help from @Koc or @cedricziel 

Thank you.

**Comment by cedricziel** [comment]
I have created a patch and added a test so that renaming the variable wouldn't rename the DocTag.

**Comment by King2500** [comment]
When can we expect the release of the new plugin version?
@Haehnchen

**Comment by cedricziel** [comment]
I'll upload a new release as soon as time allows. There's a few things to be done upfront, but it should be up next week.
