### ISSUE TITLE
Hide non public properties

### ISSUE THREAD

**Issue by digitv** [Haehnchen/idea-php-annotation-plugin#139]
Hello!
Is there some way to ignore **non public properties** of annotation class?
Now in code completion all properties are shown (incl. protected and private).
`setProperties` and `hasNoData` are protected.
![image](https://user-images.githubusercontent.com/11768817/50510083-fbf1b180-0a90-11e9-9b4a-584cdb52809d.png)

**Comment by Haehnchen** [comment]
filter for only showing public added

**Comment by Haehnchen** [comment]
hint this will break workaround in other projects:

- https://github.com/api-platform/core/pull/1788
- https://github.com/api-platform/core/pull/3204

So https://github.com/Haehnchen/idea-php-annotation-plugin/issues/112 needs to be resolved also
