### ISSUE TITLE
Import is "unused" when class name is used in @ORM\Column(type="HERE")

### ISSUE THREAD

**Issue by ikeblaster** [Haehnchen/idea-php-annotation-plugin#140]
PhpStorm 2018.3.4
Build #PS-183.5429.47, built on February 8, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Plugin version: 5.3.3

---

As title states - when I use `@ORM\Column(type="username")` then import for class named `Username` is marked as unused. Even when that class is used as type hints or in phpdoc. Custom type doesn't have to be implemented to make this issue happen (i.e. it occurs even with no child of `\Doctrine\DBAL\Types\Type` in project).

Example:
```php
<?php
use App\Domain\Username; // ❌ Import 'App\Domain\Username' is never used
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class User
{
	/**
	 * @ORM\Column(type="username", unique=true)
	 * @var Username
	 */
	private $username;
}
```

---

This **doesn't** occur when you mention `Username` in code before using ORM annotation. Thus these are working workarounds for this bug:

```php
<?php
use App\Domain\Username; // ✅ not reported
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class User
{
	/**
	 * @var Username
	 * @ORM\Column(type="username", unique=true)
	 */
	private $username;
}
```

```php
<?php
use App\Domain\Username; // ✅ not reported
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class User
{
	/**
	 * @var Username
	 */
	private $u;

	/**
	 * @ORM\Column(type="username", unique=true)
	 * @var Username
	 */
	private $username;
}
```

Also using alias with the same name... which is peculiar.

```php
<?php
use App\Domain\Username as Username; // ✅ not reported
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class User
{
	/**
	 * @ORM\Column(type="username", unique=true)
	 * @var Username
	 */
	private $username;
}
```

**Comment by mvento** [comment]
@ikeblaster Try to upgrade PHP Annotations plugins in phpstorm

**Comment by ikeblaster** [comment]
@mvento It seems to be fixed, thank you.
