### ISSUE TITLE
phpstrom 2019 not working

### ISSUE THREAD

**Issue by iiDestiny** [Haehnchen/idea-php-annotation-plugin#142]
phpstrom 2019 not working

**Comment by cedricziel** [comment]
What is not working?

**Comment by iiDestiny** [comment]
I installed the PHP annotation on the phpstrom 2019 version but there is no automatic prompt.

**Comment by iiDestiny** [comment]
![image](https://user-images.githubusercontent.com/17637481/57444270-580be400-7282-11e9-93c7-6fba6b3c40be.png)

![image](https://user-images.githubusercontent.com/17637481/57444317-740f8580-7282-11e9-8724-d6225a9ac781.png)


Use hints with swagger

**Comment by iiDestiny** [comment]
@cedricziel Hello, do you know why?

**Comment by King2500** [comment]
@iiDestiny which prompt you expect?

**Comment by iiDestiny** [comment]
I mean this plugin doesn't work in phpstrom2019

**Comment by King2500** [comment]
Yes, but what exactly? Can you write some steps to reproduce: what you do and what you expect it to do?

For me everything works in PhpStorm 2019.1. I tested completion for annotations and import etc. Everything looks OK for me.

**Comment by King2500** [comment]
And you can try to disable other plugins which may cause the problem...?

**Comment by DerManoMann** [comment]
I might have the same issue with the latest PHPStorm version (2019.1.2).

Annotations are just gray text, no autocomplete or any syntax support.

I've disabled a lot of plugins, incl. the framework plugins I use, but no difference.

**Comment by iiDestiny** [comment]
Yes, my phpstrom version is also 2019.1.2

The problem encountered is the same as @DerManoMann 


@King2500

**Comment by iiDestiny** [comment]
Thank you for your contribution. ❤️

**Comment by ipf** [comment]
I use Idea Ultimate with this plugin in Version 2019.1.2 and the plugin works as expected.

**Comment by DerManoMann** [comment]
My use case are the new openapi annotations from swagger-php.
I added a new alias and restarted too, but no luck; not sure if there is anything else to be done, tho.

I might try again with some of the default aliases, maybe that is the problem. 
With the alias there is no need for use statements in the file, right?

**Comment by jackbentley** [comment]
Working fine in PhpStorm 2019.2 for me :)

**Comment by SeinopSys** [comment]
I am also facing a similar issue, I want to use `swagger-php`'s annotations but the default mapping of `Swagger\Annotations` to `SWG` is not what the package uses anymore. I tried adding `OpenApi\Annotations` to `OA`, which is the current namespace according to the source files, but to no avail.
