### ISSUE TITLE
Doctrine repository template duplicates since last update

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-annotation-plugin#151]
Since last update I've got 2 same "Doctrine Entity Repository", see the screen attached below. As a result - I cann't modify any file template because PHPStorm couldn't save it. It is impossible to remove duplicated template because remove button is inactive.

How can I fix that?

![изображение](https://user-images.githubusercontent.com/191082/63634065-07b26980-c65a-11e9-922f-7a814219e6ce.png)

**Comment by Koc** [comment]
Got same issue on another PS installation. Maybe it caused by #150

**Comment by jackbentley** [comment]
Yeah, I've got this as well. Looks like I might've registered it twice? Will have a look into it

**Comment by toniperic** [comment]
Same here. Had to disable the plugin in order to be able to save settings.

**Comment by rgomezcasas** [comment]
Same here 🙏
