### ISSUE TITLE
Duplicated File Template: Doctrine Entity Repository

### ISSUE THREAD

**Issue by brianvarskonst** [Haehnchen/idea-php-annotation-plugin#153]
Hello, 

i wanted to create a new file template at Phpstorm but, it failed because the file template 'Doctrine Entity Repository' exists two times and i cannot delete one of them. 

![Bildschirmfoto 2019-09-03 um 21 21 37](https://user-images.githubusercontent.com/53712359/64202215-eab73b00-ce90-11e9-844c-9c0fbdae3980.png)

The Error Message: 
Cannot Save Settings:
Template with name 'Doctrine Entity Repository' already exists. Please specify a different template name.

I tried to uninstall and install phpstorm fresh, but it does not fix this error.
And if i deactivate the Plugin - i can add new File Templates, but if i activate it again - i have the same duplicated Doctrine Entity Repository - File Template.

Phpstorm Version: 2019.2
OS: Mac High Sierra - Version 10.13.6

**Comment by Grey2k** [comment]
Also have that issue on last version

**Comment by brianvarskonst** [comment]
I updated the plugin from 6.2.0 to 6.2.1 - it should be fixed now.

**Comment by Haehnchen** [comment]
fixed via new version
