### ISSUE TITLE
Deprecated class is not strike-out in the annotations suggested classes. 

### ISSUE THREAD

**Issue by PhilETaylor** [Haehnchen/idea-php-annotation-plugin#156]
forked from Twitter here: https://twitter.com/myPhilTaylor/status/1192825455105191938

I believe that the annotations plugin is at fault - Im guessing.

Basically when starting an annotation in Symfony project for `@Route` I would expect to see the deprecated class name striked-out and the non deprecated class name as normal. 

Please watch this video to understand the problem: http://screenshot.myjoom.la/7beee936aeb2

The video first shows how the deprecated class shows when writing PHP code, 

<img width="968" alt="Screenshot 2019-11-10 at 20 15 44" src="https://user-images.githubusercontent.com/400092/68550036-f37b3e80-03f6-11ea-9d24-9f02b1073347.png">

Secondly it shows the same list of classes when in an annotation

<img width="968" alt="Screenshot 2019-11-10 at 20 16 01" src="https://user-images.githubusercontent.com/400092/68550037-f8d88900-03f6-11ea-8566-e33ccd209768.png">

The difference between them is that the deprecated class is not strike-out in the annotations suggested classes. 

Is this an annotations plugin issue or a phpstorm issue?

**Comment by cedricziel** [comment]
Interesting proposition :+1:

**Comment by PhilETaylor** [comment]
Awesome - thanks for the quick change - you do not understand how helpful this will be 🎉

Although, its now just striking out the class name and not the name space:

This is what your plugin is doing:

![Screenshot 2019-11-11 at 20 01 55](https://user-images.githubusercontent.com/400092/68617077-508df780-04be-11ea-9b10-d2991ef2d206.png)

and compare that with phpStorm:
![Screenshot 2019-11-11 at 20 03 36](https://user-images.githubusercontent.com/400092/68617105-600d4080-04be-11ea-8daf-ceecb3d5ddbe.png)

Any chance you could match theirs where the whole namespace/row is strike out?

**Comment by PhilETaylor** [comment]
Also phpStorm puts deprecated classes LAST, can you do that? :-)

**Comment by cedricziel** [comment]
Hmm.. also interesting. Please open another ticket so we don't forget :)

**Comment by PhilETaylor** [comment]
Thanks for considering it :)
