### ISSUE TITLE
phpStorm puts deprecated classes last, can you do that?

### ISSUE THREAD

**Issue by PhilETaylor** [Haehnchen/idea-php-annotation-plugin#158]
Please :) 

forked from https://github.com/Haehnchen/idea-php-annotation-plugin/issues/156

This is what your plugin is doing:

![Screenshot 2019-11-11 at 20 01 55](https://user-images.githubusercontent.com/400092/68617077-508df780-04be-11ea-9b10-d2991ef2d206.png)

and compare that with phpStorm:
![Screenshot 2019-11-11 at 20 03 36](https://user-images.githubusercontent.com/400092/68617105-600d4080-04be-11ea-8daf-ceecb3d5ddbe.png)

**Comment by cedricziel** [comment]
Actually, yes - we can! :)

**Comment by PhilETaylor** [comment]
Starting to like you - very much :) 

![bitmoji](https://render.bitstrips.com/v2/cpanel/45a26a9a-8b77-41d3-82d4-db8b759e5694-ef7e7cf0-fd77-4dd2-8cb8-31cb559f8112-v1.png?transparent=1&palette=1&width=246)

**Comment by PhilETaylor** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9ab32e9a-f43b-4dd4-90f6-1c4c77b47655-ef7e7cf0-fd77-4dd2-8cb8-31cb559f8112-v1.png?transparent=1&palette=1&width=246)
