### ISSUE TITLE
whole namespace/row is not strike out

### ISSUE THREAD

**Issue by PhilETaylor** [Haehnchen/idea-php-annotation-plugin#159]
forked from https://github.com/Haehnchen/idea-php-annotation-plugin/issues/156

Its now just striking out the class name and not the name space:

This is what your plugin is doing:

![Screenshot 2019-11-11 at 20 01 55](https://user-images.githubusercontent.com/400092/68617077-508df780-04be-11ea-9b10-d2991ef2d206.png)

and compare that with phpStorm:
![Screenshot 2019-11-11 at 20 03 36](https://user-images.githubusercontent.com/400092/68617105-600d4080-04be-11ea-8daf-ceecb3d5ddbe.png)

Any chance you could match theirs where the whole namespace/row is strike out?

**Comment by cedricziel** [comment]
Hmm. I've looked it up. No easy fix. I'll look harder ;)

**Comment by PhilETaylor** [comment]
Nooooooooooo.........

**Comment by cedricziel** [comment]
It seems we use type text for... type - but the platform php plugin uses tail text - changing this now might lead to strange results in downstream plugins..

**Comment by PhilETaylor** [comment]
Means nothing to me, I'm a PHP developer not a Java developer :) but if its not possible its not possible :)

**Comment by cedricziel** [comment]
Let's see what @Haehnchen says. I've now adjusted and proposed it to the same, the original PHP plugin does to LookupElements.

**Comment by PhilETaylor** [comment]
Thanks

![bitmoji](https://render.bitstrips.com/v2/cpanel/0c62d877-a0fb-4266-89d5-4d80ec96324f-ef7e7cf0-fd77-4dd2-8cb8-31cb559f8112-v1.png?transparent=1&palette=1&width=246)
