### ISSUE TITLE
Another deprecated class place

### ISSUE THREAD

**Issue by PhilETaylor** [Haehnchen/idea-php-annotation-plugin#163]
Again, I dont know if this is controlled by your plugin, or by phpStorm, so forgive me if this is not your job to fix, just let me know and then I can raise it with phpStorm.

Continuing the theme of strikeout on deprecated classes I have found another journey.

In the annotation for a class, type the class name, then follow the prompt to "Import class", this gives a popup with 2 classes, the deprecated one, and the one we want - neither are strikeout

![Screen Recording 2019-11-12 at 04 18 PM](https://user-images.githubusercontent.com/400092/68689330-0eb98b80-0568-11ea-8f48-4b66ca4e9384.gif)

**Comment by cedricziel** [comment]
Thanks for the suggestion - yes, that's our part.

**Comment by Haehnchen** [comment]
its known providing a hint inside the line

**Comment by PhilETaylor** [comment]
Confirmed - Awesomeness.... (I would have preferred strikeout instead of deprecated but hey ho - its awesome anyway! 

<img width="715" alt="Screenshot 2020-06-03 at 22 07 53" src="https://user-images.githubusercontent.com/400092/83689369-d43c3c80-a5e6-11ea-9d51-330fd674a0f7.png">

**Comment by PhilETaylor** [comment]
oh did you have to manually specify each and every deprecation then? I assumed it was reading the `@deprecated` annotations :)
