### ISSUE TITLE
@return always uses className instead of "$this"

### ISSUE THREAD

**Issue by Leaveyou** [Haehnchen/idea-php-annotation-plugin#171]
I have discovered that in phpstorm there is n incosistency between how it generates docblocks and how idea-php-annotation-plugin plugin generates @return tags.
Given the following function that's missing a @return statement:

``` php
/**
 * @param $index
 * @param $value
 */
public function setValue($index, $value)
{
	$this->row[$index] = $value;
	return $this;
}
```
The expected behavior (and how phpstorm generates entire docblock) would be to create the docblock as following:
``` php
/**
 * @param $index
 * @param $value
 * @return $this
 */
``` 
Instead this is what the anotation is generated as:
``` php
/**
 * @param $index
 * @param $value
 * @return ClassName
 */
```

**Comment by Haehnchen** [comment]
there is no such feature inside the plugin
