### ISSUE TITLE
Add an option or stop marking keywords for BDD as [Annotations] Class not found

### ISSUE THREAD

**Issue by pkly** [Haehnchen/idea-php-annotation-plugin#202]
Recently we've started using BDD with Behat, which basically creates functions in classes like the following
```php
    /**
     * @Given /^there should be (\d+) items? in the cart$/
     */
    public function thereShouldBeItemsInTheCart(int $arg1)
```
The `@Given` keyword is used by Behat to search for appropriate functions to run during a test like

```
Scenario: Testing adding to cart
  Given there should be 1 item in the cart
  Then add another item to cart
```

The `@Given`, `@When` and `@Then` keywords via annotations are incorrectly marked as missing.
If possible it'd be great to have these be available for autocompletion at all times (no imports are required in this case), but not show up as a warning when being used without an import.
Perhaps mark them with a weak warning when they've actually been imported?

**Comment by ovgray** [comment]
+1

**Comment by Haehnchen** [comment]
done, by just adding the values but i still think about this feature in general for its noise ;)
