### ISSUE TITLE
Annotation with identical name to a method name is found as usage

### ISSUE THREAD

**Issue by theseer** [Haehnchen/idea-php-annotation-plugin#204]
Copied from https://youtrack.jetbrains.com/issue/WI-54324:

Having a method in a class and an annotation of the same name somewhere seems to incorrectly find the annotation as usage for the method.
The screenshot below shows the result for "group", which is a method name in my class as well as a PHPUnit annotation keyword.
Seems to be close, but is not exactly the same because the condition is different, as KT-29955, found in similar issues.

Simplified, it should be possible to reproduce it like this:

* Create a class with a method `foo`
* Create another class, add an annotation `/** @foo .... */`
* Select "Find usages" on the method

What is the expected result?

Show "Method not used anywhere"

What happens instead?

The annotation is shown found and shown as use.

![image](https://user-images.githubusercontent.com/111333/87568198-8f1b2800-c6c5-11ea-8a0f-5f258fcd3d46.png)

**Comment by Haehnchen** [comment]
fixed
