### ISSUE TITLE
Plugin no longer auto-completes @Route options only (other annotations work)

### ISSUE THREAD

**Issue by weaverryan** [Haehnchen/idea-php-annotation-plugin#205]
Hi!

I just noticed - along with another user https://symfonycasts.com/screencast/phpstorm/annotations#comment-4996614345 - that the auto-completion for options to `@Route()` no longer seem to work. All other annotations work fine - I tried `@ORM\Column`, and `@Gedmo\Slug`).

Missing @Route annotations (the auto-complete you see is for custom "Live Templates"):

![php-annotations](https://user-images.githubusercontent.com/121003/87876948-5327e180-c9a9-11ea-839a-2e1a5069ffc2.gif)

Functional other annotations:

<img width="781" alt="Screen Shot 2020-07-19 at 10 16 45 AM" src="https://user-images.githubusercontent.com/121003/87876951-58852c00-c9a9-11ea-96a0-50ec99ac13f5.png">

Love the plugin - just wanted to report this! 

Plugin version: 7.1.2 (same problem in 7.1.1.)
PhpStorm version: 2020.1.3 (same problem in 2020.1.2)

Thanks!

**Comment by michaelotoole** [comment]
Not just limited to @Route, also happening with other annotations like @Security/@ParamConverter.

I created an issue on the symfony plugin rather than here. Will close that Haehnchen/idea-php-symfony2-plugin#1512

**Comment by Haehnchen** [comment]
Via https://github.com/Haehnchen/idea-php-annotation-plugin/pull/182 i dropped the private property visibility. Which is the case on the classes.
Based on the doctrine-annotations the properties are public: https://www.doctrine-project.org/projects/doctrine-annotations/en/latest/custom.html#attribute-types

By looking at some Symfony annotation classes i guess instead to implement this back, the better hit rate would be using the `set*` methods in addition.

i am open for any better idea or suggestions.

**Comment by Haehnchen** [comment]
its working in latest update again. i just reverted the removal of ignoring private properties, after investigating several project and libs usages
