### ISSUE TITLE
PHP 8 Attribute Bridge

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-annotation-plugin#215]
As in PHP 8 all attributes are just the same class there should be bridge to support annotation and attributes via the same implementation. So no other plugins then need to support both.

Plugin `since` version must be changed PhpStorm 2020.3 then

**Comment by vinise** [comment]
Hi @Haehnchen ,

Any news on this?
I may do a PR if you want, if you tell me the way you think to do it :)
(directly on idea-php-symfony2-plugin or add classes to this project? as it's not any-more "annotations" i'm not sure this is the best way to do it )

Thanks

**Comment by Haehnchen** [comment]
already done
