### ISSUE TITLE
PhpStorm8: Implement new referenceContributor for DOC_IDENTIFIER

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-annotation-plugin#22]
Fix versions: EAP 138.1901
http://youtrack.jetbrains.com/issue/WI-24566.
`made any PhpDocPsiElement a ContributedReferenceHost`

**Comment by hoshsadiq** [comment]
This issue has been fixed in Intellij/PhpStorm, it would be good to have this fixed as it's still somewhat preventing me from properly using annotations (as per #26).

**Comment by Haehnchen** [comment]
done
