### ISSUE TITLE
Autocompletion sort order

### ISSUE THREAD

**Issue by AlexeyKosov** [Haehnchen/idea-php-annotation-plugin#222]
I'm not quite sure it's related to this plugin, but there's one thing that changed after updating to PhpStorm 2020.3
When I add a new property to an ORM entity, the needed annotations go at the very bottom of the autocompletion dropdown, whereas in the previous versions of PhpStorm, they were at the top. In order to add `@ORM\Column()` to a field, I could just type `@Col` and select the first option from the dropdown. Now I have to scroll to the bottom every time. Even ML-based sorting does not help.
Is it something that can be fixed or configured?
![Screenshot_9](https://user-images.githubusercontent.com/8222004/105694000-7bbd0500-5f11-11eb-996d-98c45c96045a.jpg)

**Comment by AlexeyKosov** [comment]
Looks like a duplicate of #209

**Comment by Haehnchen** [comment]
finally i got a solution; as usual sometimes it can be easy ;)
