### ISSUE TITLE
Unused imports detected for classes with generic type annotations

### ISSUE THREAD

**Issue by wimski** [Haehnchen/idea-php-annotation-plugin#224]
I'm using `@template` and `@extends`  to support generic types. The class names used in these annotations are not recognized as required imports. Is this not supported by this plugin? Will this be supported in an upcoming version?

```php
<?php

use Illuminate\Database\Eloquent\Model; // PHPStorm flags this import as unused

/**
 * @template T of Model
 */
interface RepositoryInterface
{
    /**
     * @param string $id
     * @return T|null
     */
    public function find(string $id);
}
```

```php
<?php

use App\Models\MyModel; // PHPStorm flags this import as unused

/**
 * @extends RepositoryInterface<MyModel>
 */
interface MyModelRepository extends RepositoryInterface
{
}
```

**Comment by Haehnchen** [comment]
this tags are directly handled inside PhpStorm core. maybe report the first use case to them as its not supported, but second one works
