### ISSUE TITLE
Clicking on the annotation does not highlight the corresponding `use` statement

### ISSUE THREAD

**Issue by ianfp** [Haehnchen/idea-php-annotation-plugin#23]
Consider this example:
```php
use My\BaseClass;
use My\Custom\Annotation;

/** @Annotation */
class SubClass
extends BaseClass {
}
```

When I click on `BaseClass`, either in the imports section or in the class body, both instances of the text `BaseClass` are highlighted. That's nice.

In contrast, when I click on `@Annotation`, the text `Annotation` in the imports section is not highlighted. It would be nice if custom annotations were highlighted the same way as regular classes.

**Comment by Haehnchen** [comment]
"Annotation" is blacklist

**Comment by ianfp** [comment]
No, my annotation class is not actually named `Annotation` -- sorry for the confusing example. Here's a better one from my Symfony application:

```php
namespace My\Namespace\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;

class UserController {
    /**
     * @Route("/admin/users/", name="user_list")
     * @Template
     */
    public function listAction(Request $request) {
```

Clicking on the `Request` type hint in the `listAction()` arguments highlights the `Request` in the `use` statement. By contrast, clicking on the `Route` or `Template` annotations does not highlight the corresponding class name in the `use` statement.

I'm using PhpStorm 2016.1 and I just upgraded to PHP Annotation 3.0.1.
