### ISSUE TITLE
Inline annotations are not recognized

### ISSUE THREAD

**Issue by Gadgetdude** [Haehnchen/idea-php-annotation-plugin#24]
Inline annotations are not recognised and will give a warning that there is no import for it. When I use the annotation in a docblock for a method or class it will work.

```php
<?php

namespace Gadgetdude\AcmeBundle\Controller;

use Gadgetdude\AcmeBundle\Annotation\Ignore;

/**
 * @Ignore (Is resolved correctly)
 */
class TestController
{
    /**
     * @Ignore (Is resolved correctly)
     */
    public function annotationAction()
    {
        /** @Ignore (Is not resolved, results in warning) */
        return $this->doSomethingPrivate();
    }

    // ...
}
```

Interesting is that when the annotation is only used inline (which results in a warning) does not result in a unused warning for the use statement above.

```php
<?php

namespace Gadgetdude\AcmeBundle\Controller;

use Gadgetdude\AcmeBundle\Annotation\Ignore; // No unused warning

class TestController
{
    public function annotationAction()
    {
        /** @Ignore (Is not resolved, results in warning) */
        return $this->doSomethingPrivate();
    }

    // ...
}
```

I've tested it in the last versions of PhpStorm (7.1.3, 7.1.4 and 8.0). The only other custom plugin I have enabled is the Symfony framework plugin, but I don't think that would be an issue (it never was before). The problem I'm having is a recent problem, probably introduced in 1.4 of this plugin or maybe one version earlier?

**Comment by driq** [comment]
+1
I've been running into this issue as well. It is frustrating to have PhpUnusedAliasInspection errors for valid annotations in inline docblocks.
I don't have a grasp on how big the performance penalty of processing inline docblocks would be, but I'd like you to know that this feature is wanted. So I'd love to see a fix.

**Comment by dewos** [comment]
@Haehnchen can't you make an optional "Scan the complete file for annotations" checkbox in PhpUnusedAliasInspection?

**Comment by Gadgetdude** [comment]
@dewos That is a very nice suggestion in my opinion. It would be great if it could be turned on as an option. Do you think that is a possibility, @Haehnchen?

**Comment by Duvo** [comment]
+1
_In PhpStorm 10.0.3_

Fully qualified annotation is correctly detected but annotation imports with use statement does not autocomplete, isn't detected and the warning about unused import is still there.

Any news about this huge improvement ? :)

**Comment by Haehnchen** [comment]
fixed -> todo :)

**Comment by Haehnchen** [comment]
done
