### ISSUE TITLE
Add PHP 8 Attribute generator for supported classes

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-annotation-plugin#246]
Provide Entity / Doctrine Doctrine generator for PHP 8 Attributes

```
/**
 * @ORM\Entity(repositoryClass=CrossFarmRepository::class)
 * @ORM\Table(name="cross_farm")
 */
class CrossFarm {}
```

Based on "a decision" allow generate Attributes instead of DocBlocks

```
#[ORM\Entity(repositoryClass: CrossFarmRepository::class)]
#[ORM\Table(name: "cross_farm")]
class CrossFarm {}
```

**Comment by raziel057** [comment]
Hello, is this extension intended to also support attributes? (or it should be managed by the IDE as it's a native language feature)

**Comment by Haehnchen** [comment]
i will add it here; this special libaries features are normally not added to PhpStorm itself.

**Comment by Haehnchen** [comment]
all added
