### ISSUE TITLE
Class constants as arguments are not recognised as valid imports

### ISSUE THREAD

**Issue by hoshsadiq** [Haehnchen/idea-php-annotation-plugin#26]
See below. Happy to expand on this if it's not clear.

```php
<?php

namespace Com\SomeBundle\Observer;

use Com\SomeBundle\Events\SomethingEvents; // this use statement is unrecognised, and e.g. when optimizing imports, this gets removed
use Com\SomeBundle\Event\MySomethingEvent;
use JMS\DiExtraBundle\Annotation as DI;

/**
 * @DI\Service
 */
class SomeEventObserver
{
    /**
     * @DI\Observe(SomethingEvents::PRE_UPDATE)
     */
    public function doSomething(MySomethingEvent $event)
    {
        // whatever
    }
}
```

```php
<?php

namespace Com\SomeBundle\Events;

class SomethingEvents
{
    const PRE_UPDATE = 'something.pre_update';
}
```

**Comment by lrlopez** [comment]
@Haehnchen, the API issue you opened is marked as solved. Does this mean that the plugin will be able to feature this soon?

**Comment by hoshsadiq** [comment]
@lrlopez I may be wrong but I think because it's in the same namespace is not used, or at least, PhpStorm sees it as an unnecessary import and will clean it if you optimize imports. Also, be careful with using the shortname in there when it's from a different namespace. Last time I did that, doctrine refused to find that entity until I used the full namespace in `targetEntity`.

**Comment by lrlopez** [comment]
Ah, you're right, shame on me. I use entities from different namespaces in my project but not in this case so I didn't realize what the fault was. Thanks for pointing it out!

**Comment by mickadoo** [comment]
Having the same problem.

I'm currently using fully qualified class names in all Doctrine and ParamConverters annotations in Symfony because of this, but it would be nice if I could use shortname and still have the use statement recognized as being in-use.

**Comment by hoshsadiq** [comment]
yeah, any update on this?

**Comment by Haehnchen** [comment]
done
