### ISSUE TITLE
Symfony Doctrine - Decision between Annotation and Attribute could be better

### ISSUE THREAD

**Issue by ThePatzen** [Haehnchen/idea-php-annotation-plugin#260]
Hi!

In Symfony there is a config file in /config/packages/doctrine.yml.
There you can find, if the Entity uses Attribute or Annations.

In this Config - File you can find al the needed Informations:
![image](https://user-images.githubusercontent.com/4540135/217216499-2b122b82-efc4-46da-8f3d-e3fc60a13faf.png)

Maybe this would be a awesome feature. Becaus of upgrading old Projects to php8 does no need to migrate Annotations to Attributes in the first period!

Would be awesome if you could implement this behaviour!

Thanks for your good work!

Best Regards,
David

**Comment by Haehnchen** [comment]
its not easy to resolve / find this values without much effort there.
now there is an additional check to use the parent namespace for scoping existing classes.

that's what i was think from the beginning, but missed somehow to push the implemention for latest plugin updates ;)
