### ISSUE TITLE
Annotations marked as unused in PHPStorm 2023.2 EAP

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-annotation-plugin#290]
It works fine in PHPStorm 2023.1 but stops working after update to EAP.

![image](https://github.com/Haehnchen/idea-php-annotation-plugin/assets/191082/0e192660-db91-4282-9b86-701ebca0113b)
![image](https://github.com/Haehnchen/idea-php-annotation-plugin/assets/191082/a6f40bdf-3d88-425b-843e-f2a10362c3b8)

```
PhpStorm 2023.2 EAP
Build #PS-232.8453.129, built on June 30, 2023
Licensed to PhpStorm EAP user: Konstantin Myakshin
Expiration date: July 30, 2023
Runtime version: 17.0.7+7-b1000.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-76-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    run.processes.with.pty=TRUE
    documentation.show.toolbar=true

Non-Bundled Plugins:
    com.intellij.datagen (232.8453.111)
    FrameSwitcher (4.1.1-232.7295)
    de.espend.idea.localization (0.0.6)
    Scratch (1.10)
    socrates.tabshifter (0.33)
    me.mbolotov.json.schema.generator (1.1)
    Identifier Highlighter Reloaded (1.02.1)
    com.berzanmikaili.intellij.monokai_pro (2.0.2c)
    com.vecheslav.darculaSolidTheme (1.0.3)
    com.github.jef.forest-night (1.3.0)
    monokai-pro (1.10)
    com.github.copilot (1.2.9.2684)
    com.intellij.ideolog (222.1.0.0)
    com.intellij.properties (232.8453.111)
    org.github.erikzielke.gotoproject (1.3.2)
    String Manipulation (9.9.0)
    org.plugin.dot.id (1.4.1)
    CMD Support (1.0.5)
    TabSwitch (3.0.8)
    org.intellij.RegexpTester (1.0.8)
    com.intellij.lang.jsgraphql (4.0.1)
    com.dmarcotte.handlebars (232.8453.111)
    me.mbolotov.cypress (1.5.2)
    com.jetbrains.lang.ejs (232.8453.111)
    com.nekofar.milad.intellij.nuxtjs (2.0.0)
    uk.co.ben-gibson.remote.repository.mapper (4.3.4)
    com.ppolivka.plugin.gitcleaner (1.1.4)
    com.magento.idea.magento2plugin (5.1.1)
    com.kalessil.phpStorm.phpInspectionsEA (5.0.0.0)
    lv.midiana.misc.phpstorm-plugins.deep-keys (2022.08.03.001)
    com.ruslanpolutsygan.adderremover (0.3.6)
    com.udari (0.2.4)
    com.github.woru.options-completion-phpstorm-plugin (0.0.7)
    ru.adelf.idea.dotenv (2023.2)
    NEON support (0.5.4)
    com.dryabov.phpStorm.phpregexp (0.9.7)
    de.espend.idea.php.toolbox (6.2.0)
    de.espend.idea.php.annotation (9.4.0)
    fr.adrienbrault.idea.symfony2plugin (2022.1.253)
    mobi.hsz.idea.gitignore (4.5.1)
    de.espend.idea.php.phpunit (7.1)

Current Desktop: zorin:GNOME
```

**Comment by Haehnchen** [comment]
This relies on PhpStorm feature explicitly added for this plugin. As its often breaks in EAP releases, it can just be monitored here for now. Neverless feel free to open already a PhpStorm issue.

This is noted for checking after the first non EAP build.

**Comment by alan-emiles** [comment]
I'm having this issue too in the latest snap stable release PhpStorm 2023.2

But installing previous release it works fine:
PhpStorm 2023.1.4



Build #PS-232.8660.205, built on July 28, 2023
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.2.0-25-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 5048M
Cores: 12
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    com.github.copilot (1.2.16.2847)
    com.vecheslav.darculaDarkerTheme (1.2.0)
    com.intellij.ideolog (222.1.0.0)
    String Manipulation (9.10.0)
    com.arcticicestudio.nord.jetbrains (0.13.0)
    CMD Support (1.0.5)
    in.bulma.snippet.intellij (6.2.3)
    com.kalessil.phpStorm.phpInspectionsEA (5.0.0.0)
    ru.adelf.idea.dotenv (2023.2)
    de.espend.idea.php.toolbox (6.2.0)
    de.espend.idea.php.annotation (9.4.0)
    fr.adrienbrault.idea.symfony2plugin (2022.1.253)

Current Desktop: ubuntu:GNOME

**Comment by alexbrouwer** [comment]
For those finding this issue. Make sure to upvote the issue on the Jetbrains issue tracker https://youtrack.jetbrains.com/issue/WI-73212/Import-is-never-used-False-positive-for-symfony-annotations-added-to-PHPDoc. Hopefully this gets fixed soon.

**Comment by Haehnchen** [comment]
> ... The fix will be available in the 2023.2.1 bugfix if it passes QA verification

**Comment by coolnetz** [comment]
In 2023.2.1 preview, the issue still persists for class references:

![unused_import](https://github.com/Haehnchen/idea-php-annotation-plugin/assets/55610540/bccaf6dd-233d-4153-9bd1-7399727d4998)

**Comment by Koc** [comment]
vote for https://youtrack.jetbrains.com/issue/WI-73945/Import-is-never-used-false-positive-for-a-PHP-Annotation
