### ISSUE TITLE
Unused import: "Unused statement use" reported when using Doctrine annotations

### ISSUE THREAD

**Issue by seitechsoftware** [Haehnchen/idea-php-annotation-plugin#294]
The problem is, in code inspection, PHPStorm reports:

Alias 'Doctrine\ORM\Mapping AS ORM' is never used

This has started to happen with the new version of PhpStorm 2023.2, rollback to PhpStorm 2023.1.4 solves de issue.

[https://youtrack.jetbrains.com/issue/WI-14448](https://youtrack.jetbrains.com/issue/WI-14448)

**Comment by dsentker** [comment]
I can confirm this issue with PhpStorm 2023.2

![image](https://github.com/Haehnchen/idea-php-annotation-plugin/assets/86192/3ce65f31-a656-4887-9448-d7c797a2a1bc)

**Comment by ricohumme** [comment]
I can confirm this as well. Tried reinstalling the plugin but to no avail. I found this with the Route and IsGranted annotations.

**Comment by Haehnchen** [comment]
yes, we already have an issue: https://github.com/Haehnchen/idea-php-annotation-plugin/issues/290

based on https://youtrack.jetbrains.com/issue/WI-73212/Import-is-never-used-False-positive-for-symfony-annotations-added-to-PHPDoc with the next bugfix release 2023.2.1 it should work again

**Comment by Haehnchen** [comment]
PhpStorm bugfix is out, all cases are working again, validated via tests also: https://github.com/Haehnchen/idea-php-annotation-plugin/pull/293

![image](https://github.com/Haehnchen/idea-php-annotation-plugin/assets/1011712/35813607-9d12-41ae-83f3-7b0b88ebd68a)

**Comment by wblessen** [comment]
This is still happening in 2025 ...

**Comment by wblessen** [comment]
> This is still happening in 2025 ...

Solved by installing phpStorm Extension "PHP Annotations"
