### ISSUE TITLE
Improve "Add Doctrine Column" intentions

### ISSUE THREAD

**Issue by King2500** [Haehnchen/idea-php-annotation-plugin#32]
Works:

``` php
protected<caret> $test;
protected $test<caret>;
```

Doesn't work yet:

``` php
protected $test<caret>
protected $te<caret>st;
protected <caret>$test;
<caret>protected $test;
```

Can you implement these cases as well?

This is my most common usecase:

``` php
protected $test<caret>
```

I've just written the field name (but not the semicolon yet and want to make it a Doctrine field now before completing the line with ";"). Currently I have to write the semicolon and go one char left to get the intention.

Thanks.

Tested with PhpStorm EAP 141.332

**Comment by Haehnchen** [comment]
its a basic phpstorm action here, that not reflects user behavior. next release will introduce more smarter solution.

**Comment by Haehnchen** [comment]
all should work now
