### ISSUE TITLE
MySQL syntax check interferes with Doctrine's entity referencing

### ISSUE THREAD

**Issue by mpmlj** [Haehnchen/idea-php-annotation-plugin#34]
What steps will reproduce the problem?
1. Need to have PHPStorm v9 EAP
2. Enable MySQL dialect
3. Write a Symfony/Doctrine's createQuery query containing Entity in it

What is the expected result?
Should be accepted as a valid query.

What happens instead?
PHPStorm will mark a semi-column as error.

Thank you!

![screen shot 2015-04-24 at 6 40 24 pm](https://cloud.githubusercontent.com/assets/6718777/7329815/2a3b9e28-eab2-11e4-8429-2dcde4178d57.png)

**Comment by Haehnchen** [comment]
wrong plugin see: https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/230
