### ISSUE TITLE
How to find Psi elements for concrete annotations

### ISSUE THREAD

**Issue by lisachenko** [Haehnchen/idea-php-annotation-plugin#36]
I'm building a PhpStorm extension for Go! Aspect-Oriented framework. Now I'm looking for the best way to find specific annotations and inject my annotator with pointcut grammar parser and highlightrer into these annotations.

My annotation class is one from https://github.com/lisachenko/go-aop-php/tree/master/src/Lang/Annotation (e.g. After, Around, Before, etc). How can I look for them across the project? Maybe do you have any helpers in your extension for quick check the FQDN of annotation node?

Any help will be appreciated )

**Comment by Haehnchen** [comment]
all classes are in the index:
https://github.com/Haehnchen/idea-php-annotation-plugin/blob/master/src/de/espend/idea/php/annotation/AnnotationStubIndex.java

All the magic itself happends inside `AnnotationUtil`, its also used in several other plugins:
https://github.com/Haehnchen/idea-php-annotation-plugin/blob/master/src/de/espend/idea/php/annotation/util/AnnotationUtil.java

hope that helps u

**Comment by lisachenko** [comment]
Thanks! This information is very helpful )

Am I right, that your extension point `de.espend.idea.php.annotation.PhpAnnotationReferenceProvider` can be used to provide a references from another languages to the annotations?

And one more question, probably, you can help me with it: I'm trying to inject custom language syntax (it's a pointcut query syntax) into the annotation, but looks like my PsiReferenceContributor is not capable to capture string inside annotation. 

Here is an example:

```php

use Go\Aop\Intercept\MethodInvocation;
use Go\Lang\Annotation\Around;

//....

    /**
     * This advice intercepts an execution of cacheable methods
     *
     * Logic is pretty simple: we look for the value in the cache and if it's not present here
     * then invoke original method and store it's result in the cache.
     *
     * Real-life examples will use APC or Memcache to store value in the cache
     *
     * @param MethodInvocation $invocation Invocation
     *
     * @Around("@execution(Demo\Annotation\Cacheable)")
     */
    public function aroundCacheable(MethodInvocation $invocation) {}
``` 

I have a working parser and highlighter for pointcut language, so I want to take a string like "@execution(Demo\Annotation\Cacheable)" from all `Go\Lang\Annotation\Around` annotations and inject my language there. What should I do in the order to implement such functionality?
