### ISSUE TITLE
Find Usages does not work with annotations

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-annotation-plugin#38]
I've opened `Callback` constraint and tryed to find usages of this annotation (alt+F7). No any usage found. But this annotation used in many pieces of the code.

NB: Find Usages of doctrine entities works correcly - it is displays all of the `getRepository` calls

**Comment by Haehnchen** [comment]
done, newly implementations also includ references

**Comment by Koc** [comment]
Thank you
