### ISSUE TITLE
Auto-complete without "()" by default

### ISSUE THREAD

**Issue by webmozart** [Haehnchen/idea-php-annotation-plugin#42]
Hi! :)

Thanks first of all for this wonderful plugin! I use and enjoy it a lot.

I'd love to see annotations being auto-completed without "()" by default. If I type `@Generat` + `[Ctrl]+[Space]`, then the plugin inserts:

```
@GeneratedValue()
```

although I'd like to see

```
@GeneratedValue
```

Is this feasible?

**Comment by Haehnchen** [comment]
we had this discussion long time ago. most annotations needs properties to work so is expected by most devs and allows more fluent developing.

`GeneratedValue` in this case only has one property with a default value. so in this condition its definitely i good idea to not append `()`.

btw: hoping you know that there some ORM generator/intentions eg for `id` columns ;)

**Comment by webmozart** [comment]
@Haehnchen You are right, but in that case it's easy to type `(` which will be completed with the second bracket. Removing the two brackets after auto-completion is a bit more tedious IMO and is needed (at least by me) very often. Symfony2 validation annotations, for example, very often don't have required properties.

**Comment by Haehnchen** [comment]
added application settings
