### ISSUE TITLE
Auto whitespace issues

### ISSUE THREAD

**Issue by trappar** [Haehnchen/idea-php-annotation-plugin#46]
I'm getting some pretty glaring indentation problems from this plugin. Here's a GIF of them...

![GIF of whitespace issues](http://i.imgur.com/63Xqd44.gif)

Am I doing something wrong?

**Comment by Haehnchen** [comment]
phpstorm issue. need to be reported: https://youtrack.jetbrains.com/oauth?state=%2Fissues%2FWI

**Comment by Haehnchen** [comment]
reported: https://youtrack.jetbrains.com/issue/WI-31047
