### ISSUE TITLE
Add support of the ctrl+click for the DiscriminatorMap annotation

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-annotation-plugin#47]
```php
 * @ORM\DiscriminatorMap({1="Topic", 2="Question"})
```

http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#single-table-inheritance

ctrl+click doesn't works in this case

**Comment by Haehnchen** [comment]
its work; checked also marked with annotation string. just an outdated PhpStorm index?
