### ISSUE TITLE
Add option to always use an aliased import for some annotations or namespaces

### ISSUE THREAD

**Issue by hoshsadiq** [Haehnchen/idea-php-annotation-plugin#50]
Sometimes some annotations are generally namespaces and named something else to make it easier to read. For example `Doctrine\ORM\Mapping` is generally imported as just `ORM` or `JMS\DiExtraBundle\Annotation` as just `DI`. Currently to be able to do this from scratch you have to do the following:

1. Type `@[any of the annotations within aforementioned namespace]`
1. Enter/Ctrl + Space to auto import the annotation
1. Go to imports, and remove the class name, append `as [alias name]`
1. Prefix annotation with `[alias name]\`

It's quite fiddly. It would be nice to have an option to simply list some annotations or namespaces in the settings and this would always auto import with an alias, and the annotation will be prepended with the alias name.

**Comment by Haehnchen** [comment]
done
![foo](https://cloud.githubusercontent.com/assets/1011712/14405138/09fce17c-fe88-11e5-85cd-79921073ad51.png)

**Comment by Koc** [comment]
@Haehnchen awesome! Could you ship plugin with some predefined aliases?

**Comment by Haehnchen** [comment]
@hoshsadiq, @Koc feel free to provide a list ;)

**Comment by Koc** [comment]
Which I know

```php
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use JMS\DiExtraBundle\Annotation as DI;
use JMS\Serializer\Annotation as Serializer;
use Gedmo\Mapping\Annotation as Gedmo;
```

**Comment by hoshsadiq** [comment]
That's amazing! I think @Koc has a pretty accurate defaults list. I can't think of anything else.

**Comment by Haehnchen** [comment]
so done
