### ISSUE TITLE
[API] Provide an index with annotated elements stubs

### ISSUE THREAD

**Issue by lisachenko** [Haehnchen/idea-php-annotation-plugin#53]
It would be nice to provide an API for querying the collections of `PhpNamedElement`s by annotation name. This can be useful in many places and plugins to quickly get interesting elements, for example, to find all methods, annotated with `\Sensio\Bundle\FrameworkExtraBundle\Configuration\Route`, etc

Stub index should be something like this: `<String, PhpNamedElement[]>`

**Comment by lisachenko** [comment]
Implemented this for my plugin like following: https://github.com/goaop/idea-plugin/blob/d92d57e0fe39100755f3e79ff6fa8315862bd023/src/com/aopphp/go/index/AnnotatedPhpNamedElementIndex.java

Speed of adding a back references with this index, eg. from annotation name to all usages is pretty nice, whereas without this index full scan for PhpIndex will be performed.

**Comment by Haehnchen** [comment]
also Drupal needs this https://github.com/Haehnchen/idea-php-drupal-symfony2-bridge/issues/11

**Comment by Haehnchen** [comment]
to be implemented with #79

**Comment by Haehnchen** [comment]
`AnnotationUtil.getImplementationsForAnnotation` will help. targeting PhpDocTag

**Comment by lisachenko** [comment]
Thanks! 👍
