### ISSUE TITLE
PhpDoc lexer/parser fix for nested attributes in 2016.1.1 might break (or fix) something

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-annotation-plugin#55]
will fix #8. need to update DocTag handling as they are nested now

<img width="1182" alt="screenshot 2016-04-29 16 42 16" src="https://cloud.githubusercontent.com/assets/1011712/14941052/ce4ef6ac-0f8e-11e6-8981-6212b6a252ae.png">

https://youtrack.jetbrains.com/issue/WI-22081#u=1461940977816
https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/726

**Comment by hoshsadiq** [comment]
Well, it's definitely breaking something, suddenly it can't find a lot of things (note they're all used, even the `FOS\RestBundle\Util\Codes` inside actual code not annotations but I think that one is a different issue): https://i.imgur.com/8vLlLKA.png

**Comment by Haehnchen** [comment]
closed. fixed by api migration
