### ISSUE TITLE
Support for resolving classes in Symfony Validator groups lists

### ISSUE THREAD

**Issue by taisph** [Haehnchen/idea-php-annotation-plugin#61]
The class and constant given below resolves as expected and ctrl+click works as expected:
```php
    /**
     * @Assert\NotNull(groups = MyClass::CONSTANT)
     */
    public $iAmNotNull;
```

This does not resolve:
```php
    /**
     * @Assert\NotNull(groups = {MyClass::CONSTANT, MyOtherClass::CONSTANT})
     */
    public $iAmNotNull;
```

**Comment by Haehnchen** [comment]
PhpStorm issue, but fixed by workaround in https://github.com/Haehnchen/idea-php-annotation-plugin/commit/a9aef7cacb221cf0fa91fa4d9429aba5d8954217. external issue: https://youtrack.jetbrains.com/issue/WI-32801
