### ISSUE TITLE
Support symbol icons for annotations

### ISSUE THREAD

**Issue by scaytrase** [Haehnchen/idea-php-annotation-plugin#67]
Since 2016.2.1 there are symbol icons within the project tree indicating the type of the file contents (class\interface\trait with modifiers).

IDEA has annotation symbol for annotation classes, thus we can have the same one for classes marked with `@Annotation`

http://www.jetbrains.com/help/idea/2016.2/symbols.html

https://youtrack.jetbrains.com/issue/WI-18878#comment=27-1589411

**Comment by Haehnchen** [comment]
done
