### ISSUE TITLE
Import 'x' is never used, but is in annotations

### ISSUE THREAD

**Issue by stampycode** [Haehnchen/idea-php-annotation-plugin#77]
Started happening since upgrading to PHPStorm 2016.3.1

Import an annotation class
```
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
```

Use that class in annotations, but not in any other places.
```
    /*
     * @Security("has_role('ROLE_USER')")
    */
    public function indexAction() {}
```

Expected Outcome:
The import is treated as normal, no warnings.

Actual Outcome:
The import is marked as unused. Removing this import changes the application behaviour.

**Comment by egils** [comment]
Duplicated #76
