### ISSUE TITLE
clicking on route name in template linked to incorrect function

### ISSUE THREAD

**Issue by gondo** [Haehnchen/idea-php-annotation-plugin#78]
my template:
```
<a href="{{ path('list') }}">index</a>
```

controller:
```
class AppController extends Controller
{
    ...

    /**
     * @Route("/", name="index")
     * @Template
     */
    public function indexAction(Request $request)
    {
        ...
    }

    /**
     * @Route("/list", name="list")
     * @Template
     */
    public function listAction(Request $request)
    {
        ...
    }

    ...
}
```

clicking on the route name in template opens correct controller however it points to incorrect `indexAction` function instead of correct `listAction`

PhpStorm 2016.2.1
Build #PS-162.1889.1, built on August 23, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

PHP Annotation Version: 4.2
Symfony Plugin Version: 0.12.132

**Comment by Haehnchen** [comment]
this was fixed inside Symfony Plugin
