### ISSUE TITLE
Support nested annotations

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-annotation-plugin#8]
It is possible to have annotations used inside properties of other annotations. But the plugin does not support autocompleting such case.
See http://docs.doctrine-project.org/en/latest/reference/annotations-reference.html#table for an example using it

**Comment by andytruong** [comment]
I am using 8.3, but this is still an issue.

**Comment by Haehnchen** [comment]
Status update: `Fix versions: 2016.1` ;)

**Comment by Haehnchen** [comment]
implementation: https://github.com/Haehnchen/idea-php-annotation-plugin/issues/55

**Comment by Haehnchen** [comment]
done
