### ISSUE TITLE
Imported interfaces are marked as unused when used for constant

### ISSUE THREAD

**Issue by danez** [Haehnchen/idea-php-annotation-plugin#82]
This is a similar issue like #51 which was fixed in 5d27c04cb0d4c52f5cada849cb46c004ff2babfc, but in this case it is interfaces which are marked as unused when used as constant in a annotation.

```php
use rg\core\graphql\relay\NodeInterface;

/**
 * @Query(
 *     type=NodeInterface::class
 * )
 */
class NodeQuery implements GraphQLQueryInterface {}
```

The use statement in this example is marked unused assuming NodeInterface is an interface and not a class.

I haven't checked if traits have the same problem but maybe also traits should be considered in this issue

**Comment by Haehnchen** [comment]
done
