### ISSUE TITLE
Allow @Required annotation for @Annotation classes

### ISSUE THREAD

**Issue by vudaltsov** [Haehnchen/idea-php-annotation-plugin#85]
Based on [Doctrine docs](http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/annotations.html#annotation-required)

<img width="301" alt="awdawd" src="https://cloud.githubusercontent.com/assets/2552865/23926795/67b9e634-0927-11e7-8df4-6da2f9e7f82e.png">

**Comment by Haehnchen** [comment]
already fixed
