### ISSUE TITLE
Interference with PhpStorm's Ctrl-Shift-N (Go To File)

### ISSUE THREAD

**Issue by ciliehub** [Haehnchen/idea-php-annotation-plugin#90]
After upgrading to PHPStorm 2017.2 E"Navigate -> File" stopped working correctly. Only sometimes it show up correct.

Please read [IDEA-173000](https://youtrack.jetbrains.com/issue/IDEA-173000) including my comment.

'After uninstalling the PHP Annotation plugin Ctrl-Shift-N works as expected...'

**Comment by mattsches** [comment]
Cannot confirm that. I removed both this plugin and the Symfony plugin, and the problem with Ctrl-Shift-N persists.

**Comment by ciliehub** [comment]
Mea culpa: it does NOT resolve that issue. I am so sorry...
