### ISSUE TITLE
@Template annotation can't resolve some action templates

### ISSUE THREAD

**Issue by cH40z-Lord** [Haehnchen/idea-php-annotation-plugin#92]
This issue first started occurring around 2 months ago and it's still present in 2017.2 RTM and in the newest EAP with all plugins up-to-date

Steps to reproduce:
- Create a new controller and extend from `Symfony\Bundle\FrameworkBundle\Controller\Controller`
- Import the `@Template` annotation from `Sensio\Bundle\FrameworkExtraBundle\Configuration\Template`
- Create a `listAction` like this

```php
    /**
     * @Template()
     *
     * @return array
     */
    public function listAction ()
    {
        return [];
    }
```
- PhpStorm is complaining that there's no template for the action yet, which is totally fine
![2017-09-12 at 09 10](https://user-images.githubusercontent.com/439899/30312849-914cec14-979b-11e7-9787-a590752cf9ac.jpg)
- Try create the corresponding template via <kbd>Alt+Enter</kbd> -> `Twig: Create Template`. See that the suggested template name lacks a `t` at the end of its name
![2017-09-12 at 09 10](https://user-images.githubusercontent.com/439899/30312769-3a6802d0-979b-11e7-8673-edff1987e3e2.jpg)
- When I create the suggested template, a Twig template named `lis.html.twig` is created and the annotation is no longer complaining about a missing template

Fun fact: This isn't broken in all my controllers that have a `listAction`, however it sometimes also affects other actions with the same problems (missing trailing letters). When I declare the template explicitly like `@Template("AdminBundle:JobOffer:list.html.twig")` it works too.

**Comment by tkasper** [comment]
Same here.

**Comment by Haehnchen** [comment]
fixed by:
- https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/999
- https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1000
